### ISSUE TITLE
Extraction of splicing events from user speficied gene annotation (gtf or gff)

### ISSUE THREAD

**Issue by akesarwani** [yarden/MISO#101]
For event-centric analysis, does MISO provide any tool for the extraction of splicing events from user specified gene annotation (gtf or gff). It would be extremely useful in picking events (novel) which are expressed in specific sample. Please advise me.

**Comment by yarden** [comment]
See [rnaseqlib](https://github.com/yarden/rnaseqlib) for an example of how to do this by constructing a "splice graph" (https://github.com/yarden/rnaseqlib/blob/clip/rnaseqlib/gff/gff_annotate_events.py).
