### ISSUE TITLE
Bug in credible_intervals.py

### ISSUE THREAD

**Issue by jano15** [yarden/MISO#103]
location: the file: credible_intervals.py, function: compute_credible_intervals. 

in upper_bound_indx = round((1-alpha/2)*num_samples) - 1 .

I get as result for my sample for example 2732.0 . Now this value is used to get the value in sample samples[2732.0]

and then throws this exception: 
cred_interval = [samples[lower_bound_indx], samples[upper_bound_indx]]
IndexError: only integers, slices (`:`), ellipsis (`...`), numpy.newaxis (`None`) and integer or boolean arrays are valid indices

I think the comma is the problem

fix it with: cast as an integer

**Comment by biobenkj** [comment]
Just encountered this exact issue. Wrapping the round - 1 with int() fixes the issue. Have you set up a pull request?

**Comment by sepidehparhami** [comment]
Seconded; I encountered this issue yesterday and luckily it's a quick fix. Hope to see a commit for this

**Comment by biobenkj** [comment]
Why was this closed without comment? Is this incorporated into the source code at this point?

**Comment by roryk** [comment]
Yep!

**Comment by biobenkj** [comment]
Excellent! Thanks @roryk
