### ISSUE TITLE
Sashimi plot Error: need --output-dir

### ISSUE THREAD

**Issue by marcowanger** [yarden/MISO#17]
I tried to run sashimi plot in 2 Ubuntu systems, both comes with Python 2.6.5.

When I execute sashimi plot by python python plot.py --plot-insert-len xxx.insert_len --output-dir plots/

it ways halts with "Error: need --output-dir"

I checked on the source code a bit. 

```
if options.output_dir == None:
    print "Error: need --output-dir"
    sys.exit(1)
```

It seems like .output_dir is not correctly parsed by OptionParser.

I have installed matplotlib, pysam and scipy in both systems.

**Comment by marcowanger** [comment]
The sashimi plot comes with MISO version 0.4 (http://pypi.python.org/packages/source/m/misopy/misopy-0.4.tar.gz). 

i also tried "yarden-MISO-3ffa622.zip", which does not work either

**Comment by yarden** [comment]
This was incorrectly documented -- sorry about that. "--plot-insert-len" takes two arguments, not one. It takes a *.insert_len and a settings file for sashimi plot. When it gets passed only one argument, it interprets "--output-dir" as the second, making Python think you did not pass in an --output-dir. I fixed the documentation now:

http://genes.mit.edu/burgelab/miso/docs/sashimi.html#plotting-insert-length-distributions-and-summary-statistics

**Comment by pgsin** [comment]
Good day, Yarden!
I just tried to create the length distribution graph using this way

``` bash
path2InsertL=~/test/test.bam.insert_len
path2SashimiSet=~/test/sashimi_plot_settings.txt
output=~/test/output/

sashimi_plot --plot-insert-len $path2InsertL $path2SashimiSet --output-dir $output
```

but program crashes without any error calling, only recommendations to read help? Need I change setting file, Do you have any suggestions about this? Need I change the [data] section?

Pavel
