### ISSUE TITLE
Convert GFF to Python object.

### ISSUE THREAD

**Issue by gaborcsardi** [yarden/MISO#3]
And back. Use the functions in GFF.py.

**Comment by gaborcsardi** [comment]
Done in commits cdc7db16e5f9ace2bc58, 93dfbd880039e9ee6485 and b0fe3228f8e4114562f2.

Some testing is needed for the missing values, see how these are represented in GFF.py. It would be nice to have a general testing framework.

**Comment by yarden** [comment]
This is essentially done at the Python level -- py2c_gene will convert a Python object to C (but not back)

**Comment by gaborcsardi** [comment]
This seems to be working fine.
