### ISSUE TITLE
Creating my own gff3 file

### ISSUE THREAD

**Issue by frontal** [yarden/MISO#58]
ירדן שלום

I noticed miso works on known SE exons.
I want to run it on all possible trios (including constitutives) to spot changes made by condition. (As we suspect condition could effect constitutives as well, making them cassette).

Any suggestions ?

I have created a BED file using splicetrap/TXdbgen for mm10.
I could use some help on converting it to gff3
I tried using format_convert.py on rnaseqlib but it produce only a 3 column output file.

**Comment by yarden** [comment]
See this: http://www.biostars.org/p/2/
