### ISSUE TITLE
Creating new AS annotation

### ISSUE THREAD

**Issue by ramaniak** [yarden/MISO#61]
Hello,
I work with  C. elegans and would like to use MISO for evaluating splicing changes. I notice that you have readily available annotations for Human, Mouse and Fly splice events. Would it be possible for you to point me to instructions on how to generate a similar annotation file for C. elegans? I have been reading through the documentation but have not noticed any obvious way to figure this out. Any help is much appreciated.

Thanks

**Comment by yarden** [comment]
Hi,

We do not have worm annotations currently. If you're interested in alternative splicing events (exon-centric annotation), you can generate these from transcript annotations in worm. We have some unpolished, unpublished scripts that do this (part of the rnaseqlib repository: https://github.com/yarden/rnaseqlib/blob/clip/rnaseqlib/gff/gff_make_annotation.py) that you can look it if they're helpful. All they do is parse a set of transcripts for each gene, and from it use some simple rules to define all the alternative exons, alternative splice sites, etc. which then are serialized as GFF files.  --Yarden
