### ISSUE TITLE
Cannot load misopy after installing to staged python 2.7 location using pip

### ISSUE THREAD

**Issue by kotoroshinoto** [yarden/MISO#69]
-bash-4.1$ pip2 install misopy
Requirement already satisfied (use --upgrade to upgrade): misopy in /UCHC/HPC/Everson_HPC/python-2.7/lib/python2.7/site-packages/misopy-0.4.9-py2.7-linux-x86_64.egg
Requirement already satisfied (use --upgrade to upgrade): matplotlib in /UCHC/HPC/Everson_HPC/python-2.7/lib/python2.7/site-packages (from misopy)
Requirement already satisfied (use --upgrade to upgrade): numpy>=1.5.0 in /UCHC/HPC/Everson_HPC/python-2.7/lib/python2.7/site-packages (from misopy)
Requirement already satisfied (use --upgrade to upgrade): scipy>=0.9.0 in /UCHC/HPC/Everson_HPC/python-2.7/lib/python2.7/site-packages (from misopy)
Requirement already satisfied (use --upgrade to upgrade): pysam>=0.6.0 in /UCHC/HPC/Everson_HPC/python-2.7/lib/python2.7/site-packages (from misopy)
Requirement already satisfied (use --upgrade to upgrade): six>=1.3 in /UCHC/HPC/Everson_HPC/python-2.7/lib/python2.7/site-packages (from matplotlib->misopy)
Requirement already satisfied (use --upgrade to upgrade): python-dateutil in /UCHC/HPC/Everson_HPC/python-2.7/lib/python2.7/site-packages (from matplotlib->misopy)
Requirement already satisfied (use --upgrade to upgrade): pyparsing>=1.5.6 in /UCHC/HPC/Everson_HPC/python-2.7/lib/python2.7/site-packages (from matplotlib->misopy)
Requirement already satisfied (use --upgrade to upgrade): nose>=0.11.1 in /UCHC/HPC/Everson_HPC/python-2.7/lib/python2.7/site-packages (from matplotlib->misopy)
Requirement already satisfied (use --upgrade to upgrade): mock in /UCHC/HPC/Everson_HPC/python-2.7/lib/python2.7/site-packages (from matplotlib->misopy)
Requirement already satisfied (use --upgrade to upgrade): cython>=0.20.1 in /UCHC/HPC/Everson_HPC/python-2.7/lib/python2.7/site-packages (from pysam>=0.6.0->misopy)

> > > import pysam
> > > import six
> > > import nose
> > > i>>> import cython
> > > import scipy

just to show you those load

> > > import misopy
> > > Traceback (most recent call last):
> > >   File "<stdin>", line 1, in <module>
> > > ImportError: No module named misopy
> > > import pysplicing
> > > Traceback (most recent call last):
> > >   File "<stdin>", line 1, in <module>
> > > ImportError: No module named pysplicing

**Comment by kotoroshinoto** [comment]
had pip uninstall and installed fresh, it appears to have worked this time. I don't know why it didn't before.

**Comment by yarden** [comment]
Great!
