### ISSUE TITLE
License unclear

### ISSUE THREAD

**Issue by rekado** [yarden/MISO#72]
`./docs/source/index.rst` says that the license for MISO is the "MIT/BSD license".

However, the file `./misopy/gff_utils.py` is licensed under the GPLv2+.  Likewise, `./pysplicing/src/random.c` contain various functions that are licensed under the GPLv2+.

As a GPL-licensed work cannot be rereleased under a non-copyleft license such as the MIT or BSD licenses it is unclear what license the combined work is supposed to have.  If `./misopy/gff_utils.py` and `./pysplicing/src/random.c` are an essential part of the combined work and cannot be excluded, should MISO as the combined work not also be released under the GPLv2+?

**Comment by yarden** [comment]
The license has been changed to GPLv2 to reflect this, since a portion of the code is not compatible with BSD. This has been clarified in documentation and pacakge.
