### ISSUE TITLE
Does the insert length mean fragment length?

### ISSUE THREAD

**Issue by huangyh09** [yarden/MISO#81]
It seems that the argument of insert length means the fragment length, rather than the real insert length (i.e., insert_len = read1_len + read2_len - frag_len).

**Comment by yarden** [comment]
You are correct. The terminology is wrongly used interchangeably and in retrospect we should have stuck to "fragment length". What MISO expects in paired-end mode is the fragment length.

**Comment by huangyh09** [comment]
Thanks a lot for the clarification :)
