### ISSUE TITLE
Compiling fastmiso on mac (can't find 'miso' / 'index_gff' / 'sashami_plot' executables)

### ISSUE THREAD

**Issue by cwarden45** [yarden/MISO#83]
Hi,

I have downloaded the latest version of MISO.  I ran 'python setup.py install' without any errors and I can find the python files in build/lib.macosx-10.11-x86_64-2.7/misopy.  However, I am having difficulty finding the c++ executables for fastmiso.

While the python versions work fine, I have another program that specifically needs to use 'index_gff' and 'sashimi_plot'.

Can you please help me locate these files and/or help me troubleshoot the compiling step?

Thanks,
Charles

**Comment by yarden** [comment]
This is likely an issue with `entry_points` if you installed miso using `python setup.py` and not `pip`. The executables "miso", "index_gff", etc. are made dynamically (they are Python scripts that are executable and don't have the ".py" extension, not C++ executable) by the package manager. The short term solution is to use `pip` but I'm in the process of fixing this.
