### ISSUE TITLE
Error: need --output-dir to compute Psi values.

### ISSUE THREAD

**Issue by pillailab** [yarden/MISO#95]
Hello,
I am running MISO on a slurm cluster and get the erro when i execute the standard run command. 
MISO (Mixture of Isoforms model)
Probabilistic analysis of RNA-Seq data for detecting differential isoforms
Use --help argument to view options.

Using MISO settings file: /ysm-gpfs/project/mp758/Tools/MISO/misopy-0.5.3/misopy/settings/miso_settings.txt
Error: need --output-dir to compute Psi values.
Tried different output directory locations but the error persists. Changed versions of MISO as well ( currently on misopy-0.5.3).
thanks for your help
MMPillai

**Comment by sky-peng** [comment]
Hello,
I have the same error when i was running MISO, and i don't know have to solve it.
Can you tell me how to fix this error?
Thanks very much

**Comment by UnnikrishnanLab** [comment]
Hi,
I'm facing similar problem, can you let me know how did you solve this error?
